### ISSUE TITLE
Disappearing Windmills

### ISSUE THREAD

**Issue by SilearFlare** [BTW-Community/Waila#1]
With WAILA installed, windmills just disappear in version beta 1.0.6. I suspect the same happens with water wheels and vertical windmills.

![image](https://github.com/BTW-Community/Waila/assets/5557920/ad398bac-5fbd-470c-99e3-2f5cc1f0ce80)
^ with waila
![image](https://github.com/BTW-Community/Waila/assets/5557920/6f46912d-8025-4327-9652-c681d4757be5)
^ without waila
Thank you for any help on the subject!

**Comment by limingzxc** [comment]
Already fixed this bug due to the mod accidentally blocking BTW packets
